//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dinner.Storage.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanySetting
    {
        public int CompanyID { get; set; }
        public bool ShowMenuWithImages { get; set; }
        public bool ShowMenuWithDescription { get; set; }
        public bool ShowMenuWithWeight { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
