//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dinner.Storage.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Users = new HashSet<User>();
            this.Courses = new HashSet<Course>();
            this.Feedbacks = new HashSet<Feedback>();
            this.IdentityCards = new HashSet<IdentityCard>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
        public virtual CompanySetting CompanySetting { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<IdentityCard> IdentityCards { get; set; }
    }
}
