//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dinner.Storage.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Menus = new HashSet<Menu>();
            this.Feedbacks = new HashSet<Feedback>();
        }
    
        public int ID { get; set; }
        public int CompanyID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int CourseCategoryID { get; set; }
        public bool IsDeleted { get; set; }
        public string Weight { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual CourseCategory CourseCategory { get; set; }
        public virtual ICollection<Menu> Menus { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
    }
}
