//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dinner.Storage.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public Feedback()
        {
            this.Feedback1 = new HashSet<Feedback>();
        }
    
        public int ID { get; set; }
        public short FeedbackTypeID { get; set; }
        public int CompanyID { get; set; }
        public int OwnerUserID { get; set; }
        public string Message { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> ReplyToFeedbackID { get; set; }
        public bool IsPublic { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Course Course { get; set; }
        public virtual ICollection<Feedback> Feedback1 { get; set; }
        public virtual Feedback Feedback2 { get; set; }
        public virtual FeedbackType FeedbackType { get; set; }
        public virtual User User { get; set; }
    }
}
