//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dinner.Storage.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityCard
    {
        public int CustomerCompanyID { get; set; }
        public Nullable<int> CustomerUserID { get; set; }
        public string Email { get; set; }
        public string IdentityNumber { get; set; }
        public string PublicNumber { get; set; }
        public string Name { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
    }
}
