//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dinner.Storage.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.MenuItemWishes = new HashSet<MenuItemWish>();
        }
    
        public int ID { get; set; }
        public int CourseID { get; set; }
        public System.DateTime Date { get; set; }
        public int Limit { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual ICollection<MenuItemWish> MenuItemWishes { get; set; }
    }
}
